 export const dropdowns = {
  streams: [
    { value: "Testing", label: "Testing" },
    { value: "Dental Services", label: "Dental Services" },
    { value: "Veterinary Services", label: "Veterinary Services" },
    { value: "Nursing / care service", label: "Nursing / care service" },
    { value: "Ayurveda", label: "Ayurveda" },
    { value: "Homeopathy", label: "Homeopathy" },
    { value: "Unani Medicine", label: "Unani Medicine" },
    { value: "Siddha Medicine", label: "Siddha Medicine" },
    { value: "Naturopathy", label: "Naturopathy" },
    { value: "Acupuncture", label: "Acupuncture" },
    { value: "Reiki Healing", label: "Reiki Healing" },
    { value: "Yoga", label: "Yoga" },
    { value: "Diagnostic Services", label: "Diagnostic Services" },
    { value: "Audiology", label: "Audiology" },
    { value: "Physiotherapy and Rehab", label: "Physiotherapy and Rehab" },
    { value: "Occupational Therapy", label: "Occupational Therapy" },
    { value: "Speech Therapy", label: "Speech Therapy" },
    { value: "Chiropractic Care", label: "Chiropractic Care" },
    { value: "Child development service", label: "Child development service" },
    { value: "Functional Medicine", label: "Functional Medicine" },
    { value: "Diet & Nutrition", label: "Diet & Nutrition" },
    { value: "Psychology", label: "Psychology" },
    { value: "Diagnostic Packages", label: "Diagnostic Packages" },
    { value: "Neurology", label: "Neurology" }
  ],

  specialities: [
    { value: "General", label: "General" },
    { value: "Cardiology", label: "Cardiology" },
    { value: "Dermatology", label: "Dermatology" },
    { value: "ENT", label: "ENT" },
    { value: "Orthopedics", label: "Orthopedics" },
    { value: "Pediatrics", label: "Pediatrics" },
    { value: "Gynecology", label: "Gynecology" },
    { value: "Neurology", label: "Neurology" },
    { value: "Psychiatry", label: "Psychiatry" },
    { value: "Urology", label: "Urology" },
    { value: "Ophthalmology", label: "Ophthalmology" },
    { value: "Oncology", label: "Oncology" },
    { value: "Orthodontics", label: "Orthodontics" }
  ],

  states: [
    { value: "Andaman and Nicobar Islands", label: "Andaman and Nicobar Islands" },
    { value: "Andhra Pradesh", label: "Andhra Pradesh" },
    { value: "Arunachal Pradesh", label: "Arunachal Pradesh" },
    { value: "Assam", label: "Assam" },
    { value: "Bihar", label: "Bihar" },
    { value: "Chandigarh", label: "Chandigarh" },
    { value: "Chhattisgarh", label: "Chhattisgarh" },
    { value: "Dadra and Nagar Haveli", label: "Dadra and Nagar Haveli" },
    { value: "Daman and Diu", label: "Daman and Diu" },
    { value: "Delhi", label: "Delhi" },
    { value: "Goa", label: "Goa" },
    { value: "Gujarat", label: "Gujarat" },
    { value: "Haryana", label: "Haryana" },
    { value: "Himachal Pradesh", label: "Himachal Pradesh" },
    { value: "Jammu and Kashmir", label: "Jammu and Kashmir" },
    { value: "Jharkhand", label: "Jharkhand" },
    { value: "Karnataka", label: "Karnataka" },
    { value: "Kerala", label: "Kerala" },
    { value: "Lakshadweep", label: "Lakshadweep" },
    { value: "Madhya Pradesh", label: "Madhya Pradesh" },
    { value: "Maharashtra", label: "Maharashtra" },
    { value: "Manipur", label: "Manipur" },
    { value: "Meghalaya", label: "Meghalaya" },
    { value: "Mizoram", label: "Mizoram" },
    { value: "Nagaland", label: "Nagaland" },
    { value: "Odisha", label: "Odisha" },
    { value: "Puducherry", label: "Puducherry" },
    { value: "Punjab", label: "Punjab" },
    { value: "Rajasthan", label: "Rajasthan" },
    { value: "Sikkim", label: "Sikkim" },
    { value: "Tamil Nadu", label: "Tamil Nadu" },
    { value: "Telangana", label: "Telangana" },
    { value: "Tripura", label: "Tripura" },
    { value: "Uttar Pradesh", label: "Uttar Pradesh" },
    { value: "Uttarakhand", label: "Uttarakhand" },
    { value: "West Bengal", label: "West Bengal" }
  ],

  hospitalTypes: [
    { value: "Multi-speciality hospital", label: "Multi-speciality hospital" },
    { value: "Single-speciality hospital", label: "Single-speciality hospital" },
    { value: "Polyclinic", label: "Polyclinic" },
    { value: "Single clinic", label: "Single clinic" }
  ]
};
